const en = {
    MenuSegment: {
        admin: 'Admin',
        user: 'User',
        system: 'System'
    },

    ScreenTitles: {
        home: 'Home',
        notes: 'Notes',
        search: 'Search',
        favorite: 'Favorites',
        users: 'Users',
        settings: 'Settings',
        profile: 'Profile',
        darkTheme: 'Dark theme',
        fontSize: 'Font and size settings',
        notesdetails: 'Edit note'
    },

    Auth: {
        loginTitle: 'Login',
        loginDescription: 'Small description one or two row test for more text one or two row test for more text',
        login: 'Login',
        registraton: 'Registration',
        registratonNew: 'Register new account',
        passwordForget: 'Forgot password?',
        saveLoginDetails: 'Save login details',
        accoutRemember: 'I remember my account',
        email: 'Email',
        password: 'Password',
        resetPasswordTitle: 'Reset your #/password#',
        resetPasswordDescription: 'Enter your username and a password change request will be sent to your e-mail.',
        resetPassword: 'Reset password',
        user: 'User',
        company: 'Company',
        next: 'Next',
        register: 'Register',
        changePassword: 'Change password',
        'auth/email-already-in-use': 'That email address is already in use!',
        'auth/invalid-email': 'That email address is invalid!',
        'auth/user-not-found': 'User not found',
        'auth/wrong-password': 'Wrong password',
        'creditentialsNotSaved': 'Credentials are not saved, please login to save your credentials',
        'auth/network-request-failed': 'Network request failed',
        Error: 'Error',
        resetPassword: 'Reset password',
        emailSentTitle: 'Email sent',
        emailSentDescription: 'The link to reset your password was sent to your email',
        goBack: 'Go back'
    },

    ExternalLogin: {
        googleButton: 'Continue with Google',
        facebookButton: 'Continue with Facebook',
        iosButton: 'Continue with Apple',
        windowsButton: 'Continue with Windows',
    },

    Languages: {
    },

    Themes: {
    },

    SessionExpired: {
        sessionExpired: 'Session Expired',
        sessionExpiredPatern: 'Draw a pattern to continue using the app',
        sessionExpiredPassword: 'Enter a password to continue using the app',
        Password: 'Password',
    },

    AppCenter: {
        'Downloading package': 'Downloading package...',
        'Installing update': 'Installing update...',
        'Update installed': 'Update installed.',
        'An unknown error occurred': 'An unknown error occurred.',
    },

    Common: {
        'The field is in the wrong format': 'The field is in wrong format',
        'The field contains unsupported characters': 'The field contains unsupported characters',
        'The field does not meet the minimum number of characters': 'The field does not meet the minimum number of characters',
        'The field does not meet the maximum number of characters': 'The field does not meet the maximum number of characters',
        'The field does not match the password': 'The field does not match the password',
        'The field does not match the pin': 'The field does not match the pin',
        'The field is required': 'The field is required',

        Username: 'Username',
        Password: 'Password',
        Email: 'Email',
        'Name and Surname': 'Name and Surname',

        addToFavorites: 'Add to favorites',
        copyTheTextOfTheHadith: 'Copy the text of the hadith',
        writeANoteOnTheHadith: 'Write a note on the hadith',
        textSizeAndSettings: 'Text size and settings',
        addFavouriteCategory: 'Add category',

        takeAPicture: 'Take a picture',
        choseFromGallery: 'Chose from gallery'

    },

    Intro: {
        titleintro1: 'Napredni pretraživač',
        descriptionintro1: 'Aplikacija nudi mogućnost lakog pretraživanja po pojmu ili broju hadisa, stim da imate mogućnost korištenja filtera i na taj način možete odabrati samo određene hadiske zbirke za pretragu.',
        titleintro2: 'Favoriti +',
        descriptionintro2: 'Svaki hadis možete dodati u favorite i da pri tome kreirate posebnu kategoriju. Ovo će  olakšati tematsku podijelu pa tako ćete na primjer moći imati kategoriju “Vrijednost posta” a u drugoj kategoriji “O abdestu”.',
        titleintro3: 'Bilješke',
        descriptionintro3: 'Omogućili smo naprednu funkciju pisanja bilješki na hadis. Nakon što se registrirate i logirate u mobilnu ili web aplikaciju imat ćete mogućnost pisanja bilješki te sve će biti pohranjene na vaš korisnički račun.',
        titleintro4: 'Swipe',
        descriptionintro4: 'Prateći trendove korisničkog sučelja interakciju brisanja hadisa iz bilješki i favorita smo omogućili popularnim “swipeom”.',
        titleintro5: 'Upravljanje izgledom',
        descriptionintro5: 'Aplikacija pruža mogućnost korištenja tamnog moda, odabira fontova koji su kreirani samo za čitanje knjiga te povećavanje veličine teksta hadisa.',
        close: 'Close'
    },

    Settings: {
        fontAndSizeSettings: 'Font and size settings',
        darkMode: 'Dark mode',
        hadithOfTheDay: 'Hadith of the day',
        instructionsForUse: 'Instructions for use',
        platformOfHadithConfusion: 'Platform of Hadith confusion',
        privacyPolicy: 'Privacy Policy',
        reportABug: 'Report a bug',
        on: 'On',
        off: 'Off',
        defaultByMobilePhoneSystem: 'Default by mobile phone system',
        version: 'version'
    },

    Profile: {
        deleteProfile: 'Delete profile',
        logout: 'Logout',
        deleteAccTitle: 'Delete account',
        deleteAccDescription: 'Are you sure you want to delete your account?',
        yes: 'Yes',
        no: 'No',
        logoutTitle: 'Logout',
        logoutDescription: 'Are you sure you want to loggout?',
    },

    Search: {
        searchByCollections: 'Search by collections',
    },

    Home: {
        hadithCollections: 'Hadith collections',
    },

    Collection: {
    },

    RequestErrors: {
        default: 'Unknown error',
        network: {
            401: 'Unauthenticated user',
            403: 'Insufficient permissions'
        },
        internal: {
            1: 'The requested method is not allowed',
            2: 'Login information on the system has not been forwarded',
            3: 'Username is invalid format',
            4: 'Password is invalid format',
            5: 'Login data is invalid',
            6: 'Database error',
            7: 'The POST request is incorrect format',
            8: 'The field is incorrect format',
            9: 'The entry already exists in the database',
            10: 'ID has to be passed through the GET method',
            11: 'The requested ID was not found in the database',
            12: 'One of the search parameters needs to be passed',
            13: 'The GET parameter is invalid format',
            14: 'The requested user was not found in the database',
            15: 'The requested country was not found in the database',
            16: "User doesn't have permission for the requested module / action",
            17: 'The mysql table name needs to be passed',
            18: 'Value not found in selected database',
            19: 'Error passing key / value parameters',
            20: "The file format isn't allowed",
            21: 'The category was not found in the table',
            22: 'The product was not found in the table',
            23: 'The product ID was not passed',
            24: 'The variation was not found in the table',
            25: 'The selected table is not allowed to be viewed using this method',
            26: 'Unable to find user. General error',
            27: 'The requested number was not found, or is used in one of the campaigns',
            28: 'There are no users for payout for the requested period',
            29: 'Only pending payout is allowed to be deleted',
            30: 'It is necessary to pass the parameter: status',
            31: 'Unable to switch from existing to requested status',
            32: 'The contact has been taken or is already owned by the user',
            33: 'The entry has already been received in the system',
            34: 'It is necessary to pass the status through the GET method',
            35: 'The ticket does not exist or is closed for further response',
            36: 'The user does not have an active selected payment method',
            37: 'The amount you entered is not sufficient for the selected method',
            38: 'The selected method is currently unavailable for use',
            39: 'The selected method is currently inactive on your account',
            40: 'You currently have insufficient funds in your account',
            41: 'It is necessary to pass the username through the query parameter',
            42: 'Unable to find user in the database',
            43: 'A link to reset the password has already been requested for the user. Check your spam / junk',
            44: 'Unable to find token',
            45: 'You need to re-enter the password correctly',
            46: "Error in communication with third part services",
            47: "Budget for campaign has been spent. To reactivate campaign increase budget",
            48: "Campaign rejections comment is missing",
            49: "Campaign creative rejections comment is missing",
            50: "Field character length too long",
            51: "File error upload",
            52: "Can't edit finalized payments",
            53: "Validation errors",
            54: "You need at least one of: Sub ID, Country or Device",
            55: "Subject length exceeds 256 characters",
            56: "Selected email not in allowed list of emails",
            57: "Content of email not valid format. Base64 required",
            58: "Newsletter can only be switched to status in-process",
            59: "Unable to find or edit newsletter due to it's status",
            60: "Parameter user_id is required for action",
            61: "It is necessary to first assign an account manager to the user",
            62: "The account has already been verified",
            63: "You are not marked as a user manager.",
            64: "The QR code has already been scanned.",
            65: "QR code does not exist.",
            66: "The phone number is not in the correct format",
            67: "The user has already been verified",
            68: 'It is not possible to delete the entire batch, where some QRs have already been scanned',
            69: 'Tracking and Delivery code cannot be the same.',
            76: "User already verified",
        },
        custom: {}
    },

    Countries: {
        "AF": "Afghanistan",
        "AL": "Albania",
        "DZ": "Algeria",
        "AD": "Andorra",
        "AO": "Angola",
        "AG": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BT": "Bhutan",
        "BO": "Bolivia (Plurinational State of)",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BR": "Brazil",
        "BN": "Brunei Darussalam",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "CV": "Cabo Verde",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CO": "Colombia",
        "KM": "Comoros",
        "CG": "Congo",
        "CD": "Congo, Democratic Republic of the",
        "CR": "Costa Rica",
        "HR": "Croatia",
        "CU": "Cuba",
        "CY": "Cyprus",
        "CZ": "Czechia",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "SZ": "Eswatini",
        "ET": "Ethiopia",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GR": "Greece",
        "GD": "Grenada",
        "GT": "Guatemala",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "HN": "Honduras",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran (Islamic Republic of)",
        "IQ": "Iraq",
        "IE": "Ireland",
        "IL": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JP": "Japan",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "KR": "Korea, Republic of",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "MX": "Mexico",
        "FM": "Micronesia (Federated States of)",
        "MD": "Moldova, Republic of",
        "MC": "Monaco",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "MK": "North Macedonia",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PL": "Poland",
        "PT": "Portugal",
        "QA": "Qatar",
        "RO": "Romania",
        "RU": "Russian Federation",
        "RW": "Rwanda",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "SS": "South Sudan",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SR": "Suriname",
        "SE": "Sweden",
        "CH": "Switzerland",
        "SY": "Syrian Arab Republic",
        "TJ": "Tajikistan",
        "TZ": "Tanzania, United Republic of",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TO": "Tonga",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TR": "Turkey",
        "TM": "Turkmenistan",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom of Great Britain and Northern Ireland",
        "US": "United States of America",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VE": "Venezuela (Bolivarian Republic of)",
        "VN": "Viet Nam",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe",
        "XK": "Kosovo"
    },

    Tooltip: {
    },

}

export default en;